### ISSUE TITLE
Don't sell yourself short!

### ISSUE THREAD

**Issue by oliverjam** [fac19/week7-CRaKT#39]
You README says the `PUT` endpoint doesn't work, but it worked perfectly for me.

**Comment by glrta** [comment]
We logged in, created an example (id 10) and tried updating it, but couldn't get put endpoint to work...
<img width="846" alt="Screenshot 2020-04-17 at 10 37 05" src="https://user-images.githubusercontent.com/52718181/79557446-7a190380-809a-11ea-8a97-6387a07e2f07.png">
