### ISSUE TITLE
READme

### ISSUE THREAD

**Issue by marialani** [fac19/week7-CRaKT#40]
TIme well spent, your readme outlines clear instructions on how to get set up, is informative and has great examples to guide throughout. You laid out the endpoints for your api, specifying which need authentication to be accessed and gave a brief description of what your api does.

The only suggestion I might make is to add a reference to the users stories and project goals/acceptance criteria with a brief on how you got on with them.

**Comment by glrta** [comment]
Nice job! Super easy to test the endpoints. Only thing I would update is the instructions to create the database. The user must be created before.

Great work!
