### ISSUE TITLE
Error 400 when it should be 401

### ISSUE THREAD

**Issue by glrta** [fac19/week7-CRaKT#45]
Deleting without token gave back error 400 - Bad request. Maybe the error stopped on the first catch in the examples.js deleteExample function. Not sure if it went to the catch(next) in the handlers. 
<img width="844" alt="Screenshot 2020-04-17 at 10 28 08" src="https://user-images.githubusercontent.com/52718181/79557204-14c51280-809a-11ea-9488-249cc2122420.png">

Oli raised this issue on our project board that might be of help: https://github.com/fac19/week7-BGJK/issues/18

**Comment by oliverjam** [comment]
If you don't send the auth header at all I think `400 bad request` is probably the expected response. You're not `401 unauthorized` because you never even tried to provide a token. (I think that's the logic anyway)
